# Force Node.js provider (no Caddy!)
providers = ["node"]

[phases.setup]
nixPkgs = ["nodejs_20", "pnpm"]

[phases.install]
cmds = ["pnpm install --frozen-lockfile"]

[phases.build]
cmds = ["pnpm run build"]

[start]
cmd = "node ./build/server/index.js"

[variables]
NODE_ENV = "production"
PORT = "3000"
